### Registration
POST http://localhost:7070/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Javohir",
  "surname": "Mengliboyev",
  "email": "javohscrip@gamil.com",
  "password": "Javohir1"
}

### Login
POST http://localhost:7070/api/v1/auth/authorization
Content-Type: application/json

{
  "email": "javohscript@gmail.com",
  "password": "Javohir1"
}

### Verification
PUT http://localhost:7070/api/v1/auth/verification/email/