### Registration
POST http://localhost:7070/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Shohjahon",
  "surname": "Hamdamov",
  "email": "hamdamovshohjahon2007@gmail.com",
  "password": "shohjahon2000"
}

### Login for ADMIN
POST http://localhost:7070/api/v1/auth/authorization
Content-Type: application/json

{
  "email": "hamdamovshohjahon2007@gmail.com",
  "password": "shohjahon2000"
}
### Login for User
POST http://localhost:7070/api/v1/auth/authorization
Content-Type: application/json

{
"email": "ali@gmail.com",
"password": "Ali1"
}

### Verification
PUT http://localhost:7070/api/v1/auth/verification/email/