### Registration
POST http://localhost:7070/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Jasur",
  "surname": "Jasurov",
  "email": "jasur@gmail.com",
  "password": "Jasur1"
}

### Login for ADMIN
POST http://localhost:7070/api/v1/auth/authorization
Content-Type: application/json

{
  "email": "javohscript@gmail.com",
  "password": "Javohir1"
}
### Login for User
POST http://localhost:7070/api/v1/auth/authorization
Content-Type: application/json

{
"email": "vali@gmail.com",
"password": "Vali1"
}

### Verification
PUT http://localhost:7070/api/v1/auth/verification/email/