### 1. Create Video like
PUT http://localhost:7070/api/v1/commentLike/like/959e0bff-b17d-4be7-97b2-66d123da5e3b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTM4MjI0NDYsImVtYWlsIjoidmFsaUBnbWFpbC5jb20iLCJpZCI6IjkxMWZiZjk0LThlYjYtNGQxOC1hY2FhLWUyM2I4ZTA0YTMyNSIsImV4cCI6MTY5NDQyNzI0NiwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.Q2jB91GMy7qRi73xceYc2XADtbNr6HBaevKjxDgegonKeJOBM6CRtggH099J-G0LrplQiHRyoK-wDiEFjPoG8A

### 2. Remove Video Like
PUT http://localhost:7070/api/v1/commentLike/dislike/959e0bff-b17d-4be7-97b2-66d123da5e3b
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTM4MjI0NDYsImVtYWlsIjoidmFsaUBnbWFpbC5jb20iLCJpZCI6IjkxMWZiZjk0LThlYjYtNGQxOC1hY2FhLWUyM2I4ZTA0YTMyNSIsImV4cCI6MTY5NDQyNzI0NiwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.Q2jB91GMy7qRi73xceYc2XADtbNr6HBaevKjxDgegonKeJOBM6CRtggH099J-G0LrplQiHRyoK-wDiEFjPoG8A

### 3. User Liked Video List
GET http://localhost:7070/api/v1/commentLike/get_liked_video_list_for_user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTM4MjI0NDYsImVtYWlsIjoidmFsaUBnbWFpbC5jb20iLCJpZCI6IjkxMWZiZjk0LThlYjYtNGQxOC1hY2FhLWUyM2I4ZTA0YTMyNSIsImV4cCI6MTY5NDQyNzI0NiwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.Q2jB91GMy7qRi73xceYc2XADtbNr6HBaevKjxDgegonKeJOBM6CRtggH099J-G0LrplQiHRyoK-wDiEFjPoG8A

### 4. Get User LikedVideo List By UserId
GET http://localhost:7070/api/v1/commentLike/get_liked_video_list_user_by_user_id?userId=911fbf94-8eb6-4d18-acaa-e23b8e04a325
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTM4MTk4MDIsImVtYWlsIjoiamF2b2hzY3JpcHRAZ21haWwuY29tIiwiaWQiOiJkNGFlMTE0Yi03ZDc4LTQ1YjEtOWZmMC00OGI4NTc5ZGMxMjIiLCJleHAiOjE2OTQ0MjQ2MDIsImlzcyI6IllvdXR1YmUgdGVzdCBwb3J0YWxpIn0.Rg2-PQhv4FkhJVEOcMHBXSuC-RbDXfFPYhGVIBp69GchFkbKrvZn0Q_zzPjWjuVVV9mD1rksGKbDMThdhxHxFQ