### 1. Create Video
POST localhost:7070/api/v1/video/create
Content-Type: application/json
Authorization: Bearer

{
  "id": "",
  "previewAttachId": "",
  "title": "",
  "categoryId": 1,
  "attachId": "",
  "status": "",
  "type": "",
  "description": "",
  "channelId": ""
}

### 2. Update Video Detail
PUT localhost:7070/api/v1/video/update/{{id}}
Content-Type: application/json
Authorization: Bearer

{
  "previewAttachId": "",
  "title": "",
  "categoryId": 1,
  "attachId": "",
  "status": "",
  "type": "",
  "description": "",
  "channelId": ""
}

### 3. Change Video Status
PUT localhost:7070/api/v1/video/update_status/id=?status=
Authorization: Bearer

### 4. Increase video_view Count
PUT localhost:7070/api/v1/video/open/increase_view_count/id=
Authorization: Bearer

### 5. Get Video Pagination by CategoryId
GET localhost:7070/api/v1/video/open/get_page_by_category?categoryI=1&page=1&size=5

### 6. Search video by Title
GET localhost:7070/api/v1/video/open/search_by_title?title=

### 7. Get video by tag_id with pagination
GET localhost:7070/api/v1/video/open/get_page_by_tag?tag=1&page=1&size=5

